language: java

jdk:
  - openjdk16

sudo: false

env:
  global:
    - CODECOV_TOKEN="f0a514f6-3b43-4815-af7c-e80ecde9a9c8"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - alexterentev90@gmail.com
    on_success: never # default: change
    on_failure: always # default: always